### ISSUE TITLE
Unnessasary sanity checks in updateState

### ISSUE THREAD

**Issue by kingoflolz** [ConnextProject/ethcalate-bidirectional-erc20-single#1]
Hi,

I'm developing a rust client for this contract and I think the sanity checks in updateState is unnecessary and hinder the development of bounty hunters for the contract. Because the contract checks the msg.sender is one of the participants, bounty hunters need to hold signed transactions instead of just signed state updates. signed transactions include a transaction sequence number from the originating address, which requires checking into the blockchain more often and has issues with multiple channels and how they are settled.

For example, if an address is on sequence number 42, and it has 3 channels open, it has to send 9 signed transactions, 3 for each channel with sequence number 43, 44 and 45, as one or more of them can be settled in any order. 

Thanks

**Comment by rhlsthrm** [comment]
Hi @kingoflolz, thanks for the feedback. We didn't design the contract initially for bounty hunting, but we are happy to work together with you to make the contract work for your needs. If I remove the sanity check, will that be sufficient to resolve this issue?

 ```
require(
    msg.sender == channel.agentA || msg.sender == channel.agentB,
    "Not your channel."
);
```

**Comment by kingoflolz** [comment]
Hi @rhlsthrm,

Simply removing the sanity check should resolve the issue.

Thanks for your quick response

**Comment by rhlsthrm** [comment]
https://github.com/ConnextProject/ethcalate-bidirectional-erc20-single/commit/ed109a712d1ba9fe5958708750fbfe86b032a5c6

Fixed.
